### ISSUE TITLE
Hardware stress test

### ISSUE THREAD

**Issue by JacobGlennAyers** [JeisonPham/ECE-285-Project#10]
We want to get a sense of how far we can push our evolutionary algorithms, since it will require us to train many models.

**Comment by JacobGlennAyers** [comment]
We may end up doing this on Google Colab.

**Comment by JacobGlennAyers** [comment]
Hardware constraints reduced by unrolling the noise input data of the autoencoder.

**Comment by JeisonPham** [comment]
Use CNNs
