### ISSUE TITLE
Converting weights from convex primal to non-convex dual

### ISSUE THREAD

**Issue by JacobGlennAyers** [JeisonPham/ECE-285-Project#2]
It seems that scnn already has an implementation of this that we might use

**Comment by JeisonPham** [comment]
We can leave things in terms of the convex dual and run the evolutionary algorithms on the number of sign patterns necessary. I do not know how to convert the convex cnn to primal. Although the benefit is we get interpretability as we can explain how each feature contributes to identifying and denoising the image
