### ISSUE TITLE
Testing Cuda Optimization

### ISSUE THREAD

**Issue by JacobGlennAyers** [JeisonPham/ECE-285-Project#3]
SCNN is written in PyTorch, so it likely already has everything we need

**Comment by JeisonPham** [comment]
I don't know if SCNN is a good idea. It requires us to load in the entire dataset so we might run into memory issues

**Comment by JacobGlennAyers** [comment]
Could that be feasible if we use a reduced version of MNIST? We could also downsample them images.

**Comment by JeisonPham** [comment]
MNIST is already as small as you're going to get. The 8x8 image is already small enough. We should just test it out with scnn. We can also do pytorch and the convex_nn repo. Everything is already set up

**Comment by JacobGlennAyers** [comment]
How would an alternative pytorch implementation that we go about circumvent this problem?
